Repository LibriVox/librivox-catalog, pull requests merged in 2024-12, with the labels that each got.

#234 Add edit link to Project page for administrators
  application/controllers/catalog/Page.php
  application/views/catalog/partials/book_sidebar.php
Labels: enhancement

#246 Add cover art to the API
  application/controllers/api/Feed.php
  application/libraries/Librivox_API.php
  application/views/public/temp_info/api.php
Labels: enhancement, priority:medium, needs:tests

#250 Remove unused js files
  public_html/js/catalog/advanced_search.js
  public_html/js/catalog/author.js
  public_html/js/catalog/page.js
  public_html/js/catalog/reader.js
  public_html/js/catalog/search.js
  public_html/js/catalog/sections.js
  public_html/js/common/script.js
  public_html/js/libs/jquery.columnizer.js
Labels: cleanup
